### ISSUE TITLE
web service query bug(?)

### ISSUE THREAD

**Issue by lgbouma** [spacetelescope/astrocut#13]
Greetings! First, thank you so very much for developing astrocut / tesscut! It's a very useful tool -- I've just started using it, and sailing has overall been very smooth.

Recently though, I believe I encountered a potential bug!

_Behavior_: using the TESScut web service, when I enter (RA, dec) = (85.8, -1.5) as in the attached screenshot, I am told "Cutout Error: No FFIs found for input target. Cutout not performed." However, the location specified is definitely in sector 6, camera 1, ccd 1 (see image on the right, with the lovely M42). This error seems to be returned for a number of the celestial coordinates on this CCD.

I checked the [holdings website](https://outerspace.stsci.edu/display/TESS/TESS+Holdings+Available+by+MAST+Service), which indicated that sector 6 should be fine to query.

My plan is to write up a `CubeFactory` + `CutoutFactory` routine to investigate a bit more closely, since I figure this may be because the backend database might not yet be updated through Sector 6?  Nonetheless, this seemed worth reporting, since I am likely not the only one!

Thank you again your work developing and maintaining this project!
--Luke

![Screenshot from 2019-06-04 17-35-10](https://user-images.githubusercontent.com/13185735/58915550-44239880-86ef-11e9-8317-79ba00ad8e34.png)

**Comment by lgbouma** [comment]
Tried again this morning, & the error did not reproduce (i.e. the cutout was downloaded successfully). I'll leave this issue open in case there are any relevant comments to be made, but I guess it's ready for closing!

**Comment by ceb8** [comment]
Hi! Thanks for opening this issue. My apologies for not seeing it sooner. I'm going to go ahead and close it, you are correct, it was a database issue, unfortunately tesscut can't tell when it can't find a file because it isn't there, or because the database has lost it.
