### ISSUE TITLE
`tesscut` does not appear to work right now

### ISSUE THREAD

**Issue by barentsen** [spacetelescope/astrocut#15]
I appear to be experiencing issues with TESScut.  For example, requesting a cut-out for `Pi Men` in sector 1 yields a `Cutout Error: No FFIs found for input target. Cutout not performed.`.

Example:
![Screenshot from 2019-07-17 09-50-57](https://user-images.githubusercontent.com/817669/61394624-65dc7780-a878-11e9-8c10-7f35d12f3c9a.png)

**Comment by ceb8** [comment]
This is probably because I am building the sector 12 cubes right now (hopefully this is the last sector we will be building on the same server that serves tesscut and this won't come up again). The process is nearly complete, so if you wait about half an hour and try again, it should start working.

**Comment by barentsen** [comment]
Haha ok, that makes sense, I'm happy to wait half an hour =)

**Comment by ceb8** [comment]
OK, cubing done, tesscut's back up. And the sector 12 cubes will appear momentarily.

**Comment by barentsen** [comment]
I confirm it's all working again! :+1::+1::+1::+1:
