### ISSUE TITLE
TESScut fails with some formatting for moving object names

### ISSUE THREAD

**Issue by benmontet** [spacetelescope/astrocut#50]
Thank you for making and maintaining TESSCut, it is a great service!

I've come across an issue making light curves for moving objects which I think is a function of the name used. The issue might be when forward slashes are in the object name, somewhere in the parsing of that information?

As an example, if I try to make a light curve for the comet C/2014 UN271 with the following (or through the web interface)

`https://mast.stsci.edu/tesscut/api/v0.1/moving_target/astrocut?obj_id=C%2F2014%20UN271&y=20&x=20&units=px&sector=30` 

I get a `Cutout Error: Cutout could not be performed` response. However, if I use an alternate name for the same object, Bernardinelli-Bernstein, the equivalent command (`https://mast.stsci.edu/tesscut/api/v0.1/moving_target/astrocut?obj_id=Bernardinelli-Bernstein&y=20&x=20&units=px&sector=30`) works perfectly.

My assumption from this is that it must be something in the object name, and the forward slash is the most plausible suspect to me. Have you come across this before?

**Comment by scfleming** [comment]
Thanks Ben, this seems like a character that needs to be escaped somewhere. I'll get this added to our backlog to look into.

**Comment by falkben** [comment]
Relevant section of code: https://github.com/spacetelescope/astrocut/blob/86b4a353f48ca1be1fc71c03a01d9f797199b40b/astrocut/cutout_processing.py#L424-L429

The file it's creating is using the `/` in the target name.  No excellent ways to deal with this, but we could `quote` the target name for the file creation there.
