### ISSUE TITLE
cutout error on s3-support branch

### ISSUE THREAD

**Issue by falkben** [spacetelescope/astrocut#54]
On the `s3-support` branch for making direct s3 cutouts, seeing an error with this set of input data:

```python
from astrocut import CutoutFactory

astrocut_cutter = CutoutFactory()

cube_file = 's3://stpubdata/tess/public/mast/tess-s0030-4-3-cube.fits'
coordinates = '102.7 -70.5'
cutout_size = (3, 3)
output_path = '/tmp'

astrocut_cutter.cube_cut(cube_file, coordinates, cutout_size, output_path=output_path)
```

Traceback:

```
Traceback (most recent call last):
  File "/Users/bfalk/repos/astrocut/astrocut/tests/test_small_s3_cutout.py", line 12, in <module>
    astrocut_cutter.cube_cut(cube_file, coordinates, cutout_size, output_path=output_path)
  File "/Users/bfalk/repos/astrocut/astrocut/cube_cut.py", line 736, in cube_cut
    self._parse_table_info(cube.table.data, verbose)
  File "/Users/bfalk/repos/astrocut/astrocut/cube_cut.py", line 930, in table
    return self.loop.run_until_complete(self.cube_async.table)
  File "/Users/bfalk/miniconda3/envs/astrocut/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/bfalk/repos/astrocut/astrocut/cube_cut.py", line 1018, in table
    self._table = await self.read_table()
  File "/Users/bfalk/repos/astrocut/astrocut/cube_cut.py", line 1032, in read_table
    hdu2_str = await self._read_block(hdu2_offset, length=None)
  File "/Users/bfalk/repos/astrocut/astrocut/cube_cut.py", line 1064, in _read_block
    resp = await self.s3_client.get_object(
  File "/Users/bfalk/miniconda3/envs/astrocut/lib/python3.9/site-packages/aiobotocore/client.py", line 187, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InvalidRange) when calling the GetObject operation: The requested range is not satisfiable
```

Specifying a local file for the `cube_file`, I don't see this error, and the cutout succeeds.

I'm wondering if this particular sector/file needs some special casing when reading in the table information?

@barentsen wondering if you might be able to take a look at this at some point?

**Comment by barentsen** [comment]
Thanks @falkben.  I am able to reproduce this error with the same error message.

The `InvalidRange` error occurs while reading in the data table located in HDU 2, i.e. this line fails:
```python
hdu2_str = await self._read_block(hdu2_offset, length=None)
```

This is caused by the fact that HDU2 does not appear at the expected location.  The debugger shows
```python
hdu2_offset = 134330040000
```
which makes no sense because it is equal to the size of the entire file:
```
$ aws s3 ls s3://stpubdata/tess/public/mast/tess-s0030-4-3-cube.fits --no-sign-request
2020-12-02 09:09:18 134330040000 tess-s0030-4-3-cube.fits
```

My best guess is there must be a bug in the way `hdu2_offset` is computed.  I started downloading the cube locally to have a closer look, but this may take a while due to its size (125 GB).

**Comment by falkben** [comment]
Several of the files on the s3 bucket for sector 30 are missing hdu2. We are fixing those files. I'll leave this open for the moment, but I believe that is the source of the error and will come back and close once I confirm.

**Comment by falkben** [comment]
Closing. Files have been updated in the s3 bucket and I am no longer seeing this exception.  Your comment about the file size was incredibly helpful for figuring out this bug, so thanks!
