### ISSUE TITLE
astrocut 0.10.0 release to pypi

### ISSUE THREAD

**Issue by jaymedina** [spacetelescope/astrocut#65]

**Comment by falkben** [comment]
Doesn't look like this project doesn't follow semantic versioning too closely. but I would suggest `0.10.0` instead. 

Using the same versioning system as astropy is good. They seem to use a similar system where they will omit the patch version if it's .0. For instance, 5.0 not 5.0.0.  But then they'll also create 5.0.1  See: https://pypi.org/project/astropy/#history

**Comment by snbianco** [comment]
Closing since v0.10.0 was released.
